### ISSUE TITLE
installing from cpan + bug

### ISSUE THREAD

**Issue by lourensm** [andrefs/Lingua-EN-Tokenizer-Offsets#1]
Thanks for the package...
1)I did not manage to install the package directly by calling
$ sudo cpan -f Lingua::EN::Tokenizer::Offsets

> The module Lingua::EN::Tokenizer::Offsets isn't available on CPAN.

I downloaded the gz and installed manually.
2)But then, some strings lead to error messages, e.g.:
use Lingua::EN::Tokenizer::Offsets qw/token_offsets get_tokens/;  
my $str = "Meredith, Henry (17..-18..)";
my $tokens = get_tokens($str);  
foreach my $token (@$tokens) {
        ## do something with $token
}
$ perl testl.pl

> Use of uninitialized value in addition (+) at > >/opt/local/lib/perl5/site_perl/5.12.4/Lingua/EN/Tokenizer/Offsets.pm line 209.
> Use of uninitialized value in addition (+) at >/opt/local/lib/perl5/site_perl/5.12.4/Lingua/EN/Tokenizer/Offsets.pm line 210.

Thanks,

lourenstcc att gmail dot com

**Comment by andrefs** [comment]
Hello

Thank you for the feedback.
I won't be able to pick this up right now, but I should be able to look at it on the next tuesday, and hopefully fix it and ship a new version to CPAN.

I'll let you know as soon as this has been solved.

Best regards

André

**Comment by andrefs** [comment]
I've release a new version (0.03), hopefully the bug should be fixed (I also added a test with your example).
Also, I've removed the underscore from the version number, which means that CPAN should index it soon(ish) and make it installable with cpan.

**Comment by lourensm** [comment]
thanks:
sudo cpan Lingua::EN::Tokenizer::Offsets
perl testl.pl runs without problem.
